# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-01 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='releasedate',
            field=models.DateField(null=True),
        ),
    ]
